Repository ssg-java3-240304/up-and-down, pull requests merged in 2024-08, with the labels that each got.

#4 초기설정
  src/main/java/com/up/and/down/AppController.java
  src/main/java/com/up/and/down/UpProjectApplication.java
  src/main/java/com/up/and/down/common/ImageDelete.java
  src/main/java/com/up/and/down/common/ImageUpload.java
  src/main/java/com/up/and/down/main/controller/MainController.java
  src/main/java/com/up/and/down/main/dto/TempDto.java
  src/main/java/com/up/and/down/main/entity/TempEntity.java
  src/main/java/com/up/and/down/main/repository/TempEntity.java
  src/main/java/com/up/and/down/main/service/TempService.java
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
  src/main/resources/static/css/main/style.css
  src/main/resources/static/images/rubberduck.png
  src/main/resources/static/js/main/script.js
  src/main/resources/templates/admin/adminMain.html
  src/main/resources/templates/index.html
  src/main/resources/templates/search/searchList.html
  src/test/java/com/up/and/down/UpProjectApplicationTests.java
Labels: Init

#8 init: 도메인 설계 #5
  src/main/java/com/up/and/down/AppController.java
  src/main/java/com/up/and/down/common/entity/Product.java
  src/main/java/com/up/and/down/main/controller/MainController.java
  src/main/java/com/up/and/down/main/service/MainService.java
  src/main/java/com/up/and/down/main/service/TempService.java
  src/main/resources/templates/index.html
Labels: Init

#9 Init: 검색결과 페이지 도메인 설계
  src/main/java/com/up/and/down/main/controller/MainController.java
  src/main/java/com/up/and/down/search/controller/SearchController.java
  src/main/java/com/up/and/down/search/service/SearchService.java
  src/main/resources/templates/index.html
  src/main/resources/templates/productDetail.html
  src/main/resources/templates/search.html
Labels: Init

#10 Init: 커뮤니티 디렉토리 구조 정의
  src/main/java/com/up/and/down/posts/controller/PostsController.java
  src/main/java/com/up/and/down/posts/dto/PostRequestDto.java
  src/main/java/com/up/and/down/posts/entity/Post.java
  src/main/java/com/up/and/down/posts/repository/PostRepository.java
  src/main/java/com/up/and/down/posts/service/PostService.java
  src/main/java/com/up/and/down/stomp/config/StompConfig.java
  src/main/java/com/up/and/down/stomp/controller/StompController.java
  src/main/java/com/up/and/down/stomp/dto/MessageDto.java
  src/main/resources/templates/posts/postList.html
  src/main/resources/templates/stomp/stomp.html
Labels: Init

#11 Init: 상품상세 페이지 도메인 설계 #7
  src/main/java/com/up/and/down/product/controller/ProductDetailController.java
  src/main/java/com/up/and/down/product/entity/ProductComment.java
  src/main/java/com/up/and/down/product/service/ProductDetailService.java
  src/main/resources/templates/product.html
  src/main/resources/templates/search.html
Labels: Init

#24 [상품상세] entity 작업
  build.gradle
  src/main/java/com/up/and/down/common/entity/Product.java
  src/main/java/com/up/and/down/common/entity/TravelCategory.java
  src/main/java/com/up/and/down/product/controller/ProductController.java
  src/main/java/com/up/and/down/product/entity/Comment.java
  src/main/java/com/up/and/down/product/entity/CommentHistory.java
  src/main/java/com/up/and/down/product/entity/CommentState.java
  src/main/java/com/up/and/down/product/entity/ProductComment.java
  src/main/java/com/up/and/down/product/entity/ProductCommentReply.java
  src/main/java/com/up/and/down/product/service/ProductService.java
Labels: Init

#27 Fix: entity 상속 관계 오류 해결 #26
  src/main/java/com/up/and/down/common/entity/Product.java
  src/main/java/com/up/and/down/common/entity/TravelCategory.java
  src/main/java/com/up/and/down/product/entity/Comment.java
  src/main/java/com/up/and/down/product/entity/CommentHistory.java
  src/main/java/com/up/and/down/product/entity/CommentState.java
  src/main/java/com/up/and/down/product/entity/ProductComment.java
Labels: Fix

#35 Update: 상품, 댓글, 답글 연관관계 해제
  src/main/java/com/up/and/down/common/entity/Product.java
  src/main/java/com/up/and/down/product/entity/Comment.java
  src/main/java/com/up/and/down/product/entity/CommentHistory.java
  src/main/java/com/up/and/down/product/entity/Product.java
  src/main/java/com/up/and/down/product/entity/ProductComment.java
  src/main/java/com/up/and/down/product/entity/ProductCommentReply.java
  src/main/java/com/up/and/down/product/entity/ProductInformation.java
  src/main/java/com/up/and/down/product/entity/TravelCategory.java
Labels: Update

#40 Feature/community
  src/main/java/com/up/and/down/chatroom/controller/ChatRoomController.java
  src/main/java/com/up/and/down/chatroom/dto/ChatRoomDto.java
  src/main/java/com/up/and/down/chatroom/entity/ChatRoom.java
  src/main/java/com/up/and/down/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/up/and/down/chatroom/service/ChatRoomService.java
  src/main/resources/templates/chatroom/detail.html
  src/main/resources/templates/chatroom/list.html
  src/main/resources/templates/chatroom/regist.html
  src/main/resources/templates/chatroom/update.html
Labels: Init

#85 design: 퍼블리싱 #25 #49
  src/main/resources/static/css/default.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/images/index/water-slide.png
  src/main/resources/templates/index.html
  src/main/resources/templates/product.html
Labels: Design

#97 검색결과, 상품상세 페이지 퍼블리싱
  src/main/resources/static/css/index.css
  src/main/resources/static/css/layout-default.css
  src/main/resources/static/css/product.css
  src/main/resources/static/css/search.css
  src/main/resources/static/images/product/heart-fill.png
  src/main/resources/static/images/product/heart-outline.png
  src/main/resources/static/images/product/kebab-menu-icon.png
  src/main/resources/static/images/product/reading-glasses.png
  src/main/resources/static/images/product/reply-icon.png
  src/main/resources/static/images/product/share.png
  src/main/resources/templates/product.html
  src/main/resources/templates/search.html
Labels: Design

#100 커뮤니티 채팅창 퍼블리싱
  src/main/java/com/up/and/down/chatroom/controller/ChatController.java
  src/main/java/com/up/and/down/chatroom/controller/ChatStompController.java
  src/main/java/com/up/and/down/chatroom/dto/ChatDto.java
  src/main/java/com/up/and/down/chatroom/entity/Chat.java
  src/main/java/com/up/and/down/chatroom/entity/ChatRoom.java
  src/main/java/com/up/and/down/chatroom/entity/ChatRoomMember.java
  src/main/java/com/up/and/down/chatroom/repository/ChatRepository.java
  src/main/java/com/up/and/down/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/up/and/down/chatroom/service/ChatService.java
  src/main/java/com/up/and/down/config/chat/ChatConfig.java
  src/main/java/com/up/and/down/config/webSecurity/WebSecurityConfig.java
  src/main/resources/static/css/chat.css
  src/main/resources/templates/chatroom/chat.html
  src/main/resources/templates/layout/header-n-side.html
  src/test/java/com/up/and/down/chatroom/service/ChatServiceTest.java
Labels: Feat

#101 Update(src/main/resources/static/css/chat.css): chat.css 글씨 색상 수정 #96
  src/main/resources/static/css/chat.css
Labels: Update

#103 Update(src/main/resources/application.yaml): application.yaml auto 수정
  src/main/resources/application.yaml
Labels: Update

#129 Update(src/main/java/com/up/and/down/user/member, src/main/java/com/up/and/down/auth/service, src/main/resources/templates/login): sns 로그인(네이버) #34
  build.gradle
  src/main/java/com/up/and/down/auth/service/AuthService.java
  src/main/java/com/up/and/down/config/webSecurity/WebSecurityConfig.java
  src/main/java/com/up/and/down/user/member/controller/MemberController.java
  src/main/java/com/up/and/down/user/member/controller/NaverSNSController.java
  src/main/java/com/up/and/down/user/member/dto/MemberDto.java
  src/main/java/com/up/and/down/user/member/dto/NaverProfileDto.java
  src/main/java/com/up/and/down/user/member/entity/Member.java
  src/main/java/com/up/and/down/user/member/entity/SNSMember.java
  src/main/java/com/up/and/down/user/member/repository/SNSMemberRepository.java
  src/main/java/com/up/and/down/user/member/service/MemberService.java
  src/main/java/com/up/and/down/user/member/service/NaverSNSService.java
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/main/resources/templates/join/member/privacyInfo.html
  src/main/resources/templates/login/memberLogin.html
Labels: Update

#130 product entity 수정
  src/main/java/com/up/and/down/product/entity/Comment.java
  src/main/java/com/up/and/down/product/entity/CommentHistory.java
  src/main/java/com/up/and/down/product/entity/CommentState.java
  src/main/java/com/up/and/down/product/entity/Destination.java
  src/main/java/com/up/and/down/product/entity/ProductComment.java
  src/main/java/com/up/and/down/product/entity/ProductCommentReply.java
  src/main/java/com/up/and/down/product/entity/ProductGroup.java
  src/main/java/com/up/and/down/product/entity/ProductInformation.java
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/main/resources/application.yaml
Labels: Feat, Update

#133 Elasticsearch 적용 및 Test 코드 작성
  src/main/java/com/up/and/down/config/elastic/ElasticConfig.java
  src/main/java/com/up/and/down/main/controller/MainController.java
  src/main/java/com/up/and/down/main/dto/TempDto.java
  src/main/java/com/up/and/down/main/entity/TempEntity.java
  src/main/java/com/up/and/down/main/repository/TempEntity.java
  src/main/java/com/up/and/down/main/service/MainService.java
  src/main/java/com/up/and/down/product/entity/Destination.java
  src/main/java/com/up/and/down/product/entity/Product.java
  src/main/java/com/up/and/down/product/entity/ProductGroup.java
  src/main/java/com/up/and/down/product/entity/ProductInformation.java
  src/main/java/com/up/and/down/product/entity/TravelCategory.java
  src/main/java/com/up/and/down/product/repository/ProductGroupRepository.java
  src/main/java/com/up/and/down/product/repository/ProductRepository.java
  src/main/java/com/up/and/down/product/service/ProductService.java
  src/main/java/com/up/and/down/search/entity/ProductGroupDoc.java
  src/main/java/com/up/and/down/search/repository/ProductGroupDocRepository.java
  src/main/java/com/up/and/down/search/service/SearchService.java
  src/main/resources/application.yaml
  src/test/java/com/up/and/down/search/service/DataBaseTest.java
  src/test/java/com/up/and/down/search/service/ElasticsearchTest.java
Labels: Feat, Test

#138 [메인페이지] 검색하기 기능
  src/main/java/com/up/and/down/config/webSecurity/WebSecurityConfig.java
  src/main/java/com/up/and/down/product/entity/ProductGroup.java
  src/main/java/com/up/and/down/search/controller/SearchController.java
  src/main/java/com/up/and/down/search/entity/ProductGroupDoc.java
  src/main/java/com/up/and/down/search/repository/ProductGroupDocRepository.java
  src/main/java/com/up/and/down/search/service/SearchService.java
  src/main/resources/application.yaml
  src/main/resources/static/css/default.css
  src/main/resources/static/css/index.css
  src/main/resources/static/images/banner-image.png
  src/main/resources/templates/index.html
  src/test/java/com/up/and/down/search/service/ElasticsearchTest.java
Labels: Feat

#139 [FEAT] 실시간 최다 검색 상위 4개 노출 #111
  src/main/java/com/up/and/down/config/webSecurity/WebSecurityConfig.java
  src/main/java/com/up/and/down/main/controller/MainController.java
  src/main/java/com/up/and/down/main/service/MainService.java
  src/main/java/com/up/and/down/product/entity/ProductGroup.java
  src/main/java/com/up/and/down/search/controller/SearchController.java
  src/main/resources/templates/index.html
Labels: Feat

#142 [FEAT] 테마 추가 #140
  src/main/java/com/up/and/down/product/entity/ProductGroup.java
  src/main/java/com/up/and/down/product/entity/SearchKeyword.java
  src/main/java/com/up/and/down/product/entity/TravelTheme.java
Labels: Feat

#146 [메인페이지] 테마별 조회
  src/main/java/com/up/and/down/product/entity/Destination.java
  src/main/java/com/up/and/down/product/entity/Product.java
  src/main/java/com/up/and/down/product/entity/ProductGroup.java
  src/main/java/com/up/and/down/product/entity/ProductInformation.java
  src/main/java/com/up/and/down/product/entity/SearchKeyword.java
  src/main/java/com/up/and/down/search/controller/SearchController.java
  src/main/resources/static/css/index.css
  src/main/resources/static/images/index/Nature.png
  src/main/resources/static/images/index/Relaxation.png
  src/main/resources/static/images/index/Romantic.png
  src/main/resources/static/images/index/banner-image.png
  src/main/resources/static/images/rubberduck.png
  src/main/resources/templates/fragments/admin/aside.html
  src/main/resources/templates/index.html
  src/test/java/com/up/and/down/search/service/ElasticsearchTest.java
Labels: Feat

#152 [메인페이지] 디자인 수정
  src/main/java/com/up/and/down/product/entity/ProductGroup.java
  src/main/java/com/up/and/down/product/entity/ProductInformation.java
  src/main/resources/static/css/index.css
  src/main/resources/templates/index.html
Labels: Design

#153 [검색결과-검색] 검색결과 목록 노출
  build.gradle
  src/main/java/com/up/and/down/main/controller/MainController.java
  src/main/java/com/up/and/down/main/service/MainService.java
  src/main/java/com/up/and/down/product/entity/Product.java
  src/main/java/com/up/and/down/product/entity/ProductGroup.java
  src/main/java/com/up/and/down/product/entity/ProductInformation.java
  src/main/java/com/up/and/down/product/entity/SearchKeyword.java
  src/main/java/com/up/and/down/search/controller/SearchController.java
  src/main/java/com/up/and/down/search/entity/ProductGroupDoc.java
  src/main/java/com/up/and/down/search/repository/ProductGroupDocRepository.java
  src/main/java/com/up/and/down/search/service/ProductGroupToEntityService.java
  src/main/java/com/up/and/down/search/service/ProductListJsonConvertService.java
  src/main/java/com/up/and/down/search/service/SearchService.java
  src/main/resources/static/css/index.css
  src/main/resources/static/css/layout-default.css
  src/main/resources/static/css/search.css
  src/main/resources/static/images/index/banner-image.png
  src/main/resources/templates/fragments/left-side-nav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/search.html
  src/test/java/com/up/and/down/search/service/ElasticsearchTest.java
Labels: Feat

#154 design: 검색결과 없음 #53
  src/main/resources/static/css/search.css
  src/main/resources/templates/search.html
Labels: Design

#155 [검색결과] 검색 결과 목록 노출
  src/main/java/com/up/and/down/product/entity/ProductGroup.java
  src/main/java/com/up/and/down/search/controller/SearchController.java
  src/main/java/com/up/and/down/search/controller/SearchSort.java
  src/main/java/com/up/and/down/search/entity/ProductGroupDoc.java
  src/main/java/com/up/and/down/search/repository/ProductGroupDocRepository.java
  src/main/java/com/up/and/down/search/service/ProductGroupToEntityService.java
  src/main/java/com/up/and/down/search/service/SearchService.java
  src/main/resources/static/css/search.css
  src/main/resources/templates/search.html
  src/test/java/com/up/and/down/search/service/ElasticsearchTest.java
Labels: Feat

#157 [검색결과] 사용자는 사이드 네비에서 테마별 검색을 할 수 있다.
  src/main/java/com/up/and/down/product/entity/TravelTheme.java
  src/main/java/com/up/and/down/search/controller/SearchController.java
  src/main/java/com/up/and/down/search/service/SearchService.java
  src/main/resources/static/css/index.css
  src/main/resources/static/css/layout-default.css
  src/main/resources/static/images/index/banner-image.png
  src/main/resources/static/images/index/nature.png
  src/main/resources/static/images/index/relaxation.png
  src/main/resources/static/images/index/romantic.png
  src/main/resources/static/images/index/water-slide.png
  src/main/resources/templates/fragments/left-side-nav.html
  src/main/resources/templates/fragments/right-side-nav.html
  src/main/resources/templates/index.html
Labels: Feat

#162 [상품상세] 공유하기 좋아요 구현
  src/main/java/com/up/and/down/auth/controller/AuthController.java
  src/main/java/com/up/and/down/auth/principal/AuthPrincipal.java
  src/main/java/com/up/and/down/config/webSecurity/CustomAuthenticationSuccessHandler.java
  src/main/java/com/up/and/down/config/webSecurity/WebSecurityConfig.java
  src/main/java/com/up/and/down/product/controller/ProductController.java
  src/main/java/com/up/and/down/product/entity/ProductGroup.java
  src/main/java/com/up/and/down/product/response/LikeResponse.java
  src/main/java/com/up/and/down/product/response/LikeState.java
  src/main/java/com/up/and/down/product/service/ProductService.java
  src/main/java/com/up/and/down/search/entity/ProductGroupDoc.java
  src/main/java/com/up/and/down/search/service/SearchService.java
  src/main/java/com/up/and/down/user/member/entity/Member.java
  src/main/java/com/up/and/down/user/member/service/UserService.java
  src/main/resources/static/css/index.css
  src/main/resources/static/css/product.css
  src/main/resources/static/js/product.js
  src/main/resources/templates/product.html
Labels: Feat

#163 [커뮤니티] 채팅 목록 노출
  src/main/java/com/up/and/down/auth/controller/AuthController.java
  src/main/java/com/up/and/down/chatroom/controller/ChatRoomController.java
  src/main/java/com/up/and/down/chatroom/controller/ChatRoomRestController.java
  src/main/java/com/up/and/down/chatroom/dto/ChatRoomDto.java
  src/main/java/com/up/and/down/chatroom/dto/ChatRoomListResponseDto.java
  src/main/java/com/up/and/down/chatroom/dto/ChatRoomResponseDto.java
  src/main/java/com/up/and/down/chatroom/dto/ShowChatRoomDto.java
  src/main/java/com/up/and/down/chatroom/entity/ChatRoom.java
  src/main/java/com/up/and/down/chatroom/entity/ChatRoomMember.java
  src/main/java/com/up/and/down/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/up/and/down/chatroom/service/ChatRoomService.java
  src/main/java/com/up/and/down/common/ImageImport.java
  src/main/java/com/up/and/down/config/elastic/ElasticConfig.java
  src/main/java/com/up/and/down/config/webSecurity/CustomAuthenticationSuccessHandler.java
  src/main/java/com/up/and/down/product/controller/ProductController.java
  src/main/java/com/up/and/down/product/service/ProductService.java
  src/main/java/com/up/and/down/search/controller/SearchController.java
  src/main/java/com/up/and/down/search/entity/ProductGroupDoc.java
  src/main/java/com/up/and/down/search/service/SearchService.java
  src/main/java/com/up/and/down/user/member/service/MemberService.java
  src/main/resources/application.yaml
  src/main/resources/static/css/chatroom/list.css
  src/main/resources/static/js/chatroom/list.js
  src/main/resources/static/js/chatroom/list2.js
  src/main/resources/templates/chatroom/list.html
  src/main/resources/templates/chatroom/list2.html
  src/test/java/com/up/and/down/chatRoom/ChatRoomTest.java
Labels: Feat

#173 README 수정
  README.md
  src/main/java/com/up/and/down/config/webSecurity/CustomAuthenticationSuccessHandler.java
  src/main/java/com/up/and/down/config/webSecurity/WebSecurityConfig.java
  src/main/java/com/up/and/down/user/member/service/GoogleSNSService.java
  src/main/java/com/up/and/down/user/member/service/KakaoSNSService.java
  src/main/java/com/up/and/down/user/member/service/NaverSNSService.java
  src/main/resources/application.yaml
  src/main/resources/static/js/chatroom/chat.js
  src/main/resources/static/js/chatroom/list.js
  src/main/resources/static/js/product.js
  src/main/resources/templates/admin/stat/loginInfo.html
  src/main/resources/templates/admin/stat/productInfo.html
  src/main/resources/templates/join/admin/adminAccountInfo.html
  src/main/resources/templates/join/member/privacyInfo.html
Labels: Feat, Fix
